apiVersion: v1
kind: Pod
metadata:
  name: wasm-server
spec:
  restartPolicy: Always

  initContainers:
  - name: oras-pull
    image: debian:bookworm-slim
    command:
      - /bin/sh
      - -c
      - |
        set -e
        apt-get update
        apt-get install -y ca-certificates curl tar

        curl -L https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_linux_amd64.tar.gz \
          | tar -xz -C /usr/local/bin oras

        rm -rf /opt/wasm/*
        oras pull --plain-http 192.168.0.118:32000/wasm-inference:debug -o /opt/wasm

        mv /opt/wasm/bundle/* /opt/wasm/
        rmdir /opt/wasm/bundle

        ls -R /opt/wasm
    volumeMounts:
      - name: wasm
        mountPath: /opt/wasm

  containers:
  - name: server
    image: debian:bookworm-slim
    command: ["/opt/wasm/apps/server"]
    env:
      - name: WASM_MODULE
        value: /opt/wasm/apps/inference.wasm
      - name: MODELS_DIR
        value: /opt/wasm/models
      - name: LD_LIBRARY_PATH
        value: /home/node1/libtorch/lib
    volumeMounts:
      - name: wasm
        mountPath: /opt/wasm
      - name: libtorch
        mountPath: /home/node1/libtorch

  volumes:
    - name: wasm
      hostPath:
        path: /opt/wasm
        type: DirectoryOrCreate
    - name: libtorch
      hostPath:
        path: /home/node1/libtorch
        type: Directory
